apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexvion.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  APPLICATION_NAME: {{ .Values.config.applicationName | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  APPLICATION_PORT: {{ .Values.config.applicationPort | quote }}
