apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexvion.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.secret.appSecret | quote }}
