replicaCount: 2

image:
  repository: purvaawankhede/nexvion
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 80

config:
  applicationName: Nexvion
  environment: production
  applicationPort: "80"

secret:
  appSecret: nexvion-demo-secret

ingress:
  enabled: true
  className: nginx
  host: nexvion.local
