input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "project" => "Nexvion"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nexvion-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
